syntax = "proto3";

package user;

option java_package = "com.ndhuy.proto_library.user";
option java_outer_classname = "UserProto";

message AuthRequest {
    string username = 1;
    string password = 2;
}

message AuthResponse {
    string uuid = 1;
    string name = 2;
    string email = 3;
    bool is_valid = 4;
}

message RegisterRequest {
    string username = 1;
    string password = 2;
    string email = 3;
    string phone = 4;
    string fullName = 5;
}

message RegisterReponse {
    string uuid = 1;
}

service UserService {
    rpc Authenticate(AuthRequest) returns (AuthResponse);
    rpc Register(RegisterRequest) returns (RegisterReponse);
}


